Update ch2.js - q16 explanation
austintackaberry/ydkjs-exercises pull request #266
Opened 2021-08-04 17:28 UTC by RandyBoBandy92

Appears to have been written backwards. I will reference the YDKJS on nested scopes as evidence to support my edit.
https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/up%20%26%20going/ch2.md#nested-scopes
```js
function foo() {
	var a = 1;

	function bar() {
		var b = 2;

		function baz() {
			var c = 3;

			console.log( a, b, c );	// 1 2 3
		}

		baz();
		console.log( a, b );		// 1 2
	}

	bar();
	console.log( a );				// 1
}

foo();
```

2021-08-04 17:30 UTC, RandyBoBandy92 commented
I also missed a typo... says vairables. Sorry I am new to making github PR's, I don't know how to change it now.

2021-08-09 19:11 UTC, austintackaberry requested changes
Thanks for the fix! Left a couple comments for small sp/grammar fixes

2021-08-09 19:11 UTC, austintackaberry commented on src/data/UpGoing/ch2.js
> +    This means that if you declare a function within a function, the inner function is able to access the vairables declared inside it's parent function.
grammar: should be `inside its parent function`

2021-08-09 19:11 UTC, austintackaberry commented on src/data/UpGoing/ch2.js
> +    However, the parent/outer function cannot access it's child/inner function's scope.`,
grammar: should be `inside its child/inner function's scope`

2021-08-09 19:11 UTC, austintackaberry commented on src/data/UpGoing/ch2.js
> +    This means that if you declare a function within a function, the inner function is able to access the vairables declared inside it's parent function.
sp: `vairables`

2021-08-09 19:15 UTC, austintackaberry commented
> Sorry I am new to making github PR's, I don't know how to change it now.

Try doing the following:
1. Make the change
2. Run `git add .`
3. Run `git commit -m "some message"`
4. Run `git push origin patch-2`

The change will then be reflected in your branch on github and will be automatically added to the PR

2021-08-09 23:11 UTC, RandyBoBandy92 commented
> > Sorry I am new to making github PR's, I don't know how to change it now.
> 
> Try doing the following:
> 
>     1. Make the change
> 
>     2. Run `git add .`
> 
>     3. Run `git commit -m "some message"`
> 
>     4. Run `git push origin patch-2`
> 
> 
> The change will then be reflected in your branch on github and will be automatically added to the PR

Thanks for the help. I believe I've got it sorted now.

2021-08-10 16:30 UTC, austintackaberry approved these changes
Looks good, thanks!

2021-08-10 16:30 UTC, merged